version: '3.4'

services:
  ubee.db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  ubee.api:
    image: ${DOCKER_REGISTRY-}ubeeapi
    build:
      context: .
      dockerfile: src/uBee.Api/Dockerfile
