// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uBee.Persistence;

#nullable disable

namespace uBee.Persistence.Migrations
{
    [DbContext(typeof(uBeeContext))]
    partial class uBeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("uBee.Domain.Entities.BeeContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("beecontracts", (string)null);
                });

            modelBuilder.Entity("uBee.Domain.Entities.ContractedHive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeeContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HiveId")
                        .HasColumnType("int");

                    b.Property<int>("IdBeeContract")
                        .HasColumnType("int");

                    b.Property<int>("IdHive")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BeeContractId");

                    b.HasIndex("HiveId");

                    b.HasIndex("IdBeeContract");

                    b.HasIndex("IdHive");

                    b.ToTable("contractedhives", (string)null);
                });

            modelBuilder.Entity("uBee.Domain.Entities.Hive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("hives", (string)null);
                });

            modelBuilder.Entity("uBee.Domain.Entities.Location", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("DDD");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "São Paulo - Capital",
                            Number = 11
                        },
                        new
                        {
                            Id = (byte)2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "São José dos Campos e Região",
                            Number = 12
                        },
                        new
                        {
                            Id = (byte)3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Baixada Santista e Região",
                            Number = 13
                        },
                        new
                        {
                            Id = (byte)4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Bauru e Região",
                            Number = 14
                        },
                        new
                        {
                            Id = (byte)5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Sorocaba e Região",
                            Number = 15
                        },
                        new
                        {
                            Id = (byte)6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ribeirão Preto e Região",
                            Number = 16
                        },
                        new
                        {
                            Id = (byte)7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "São José do Rio Preto e Região",
                            Number = 17
                        },
                        new
                        {
                            Id = (byte)8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Presidente Prudente e Região",
                            Number = 18
                        },
                        new
                        {
                            Id = (byte)9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Campinas e Região",
                            Number = 19
                        },
                        new
                        {
                            Id = (byte)10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Rio de Janeiro - Capital",
                            Number = 21
                        },
                        new
                        {
                            Id = (byte)11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Campos dos Goytacazes e Região",
                            Number = 22
                        },
                        new
                        {
                            Id = (byte)12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Volta Redonda e Região",
                            Number = 24
                        },
                        new
                        {
                            Id = (byte)13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Vitória e Região",
                            Number = 27
                        },
                        new
                        {
                            Id = (byte)14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Sul do Espírito Santo",
                            Number = 28
                        },
                        new
                        {
                            Id = (byte)15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Belo Horizonte e Região",
                            Number = 31
                        },
                        new
                        {
                            Id = (byte)16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Juiz de Fora e Região",
                            Number = 32
                        },
                        new
                        {
                            Id = (byte)17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Governador Valadares e Região",
                            Number = 33
                        },
                        new
                        {
                            Id = (byte)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Uberlândia e Região",
                            Number = 34
                        },
                        new
                        {
                            Id = (byte)19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Poços de Caldas e Região",
                            Number = 35
                        },
                        new
                        {
                            Id = (byte)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Divinópolis e Região",
                            Number = 37
                        },
                        new
                        {
                            Id = (byte)21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Montes Claros e Região",
                            Number = 38
                        },
                        new
                        {
                            Id = (byte)22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Curitiba e Região",
                            Number = 41
                        },
                        new
                        {
                            Id = (byte)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ponta Grossa e Região",
                            Number = 42
                        },
                        new
                        {
                            Id = (byte)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Londrina e Região",
                            Number = 43
                        },
                        new
                        {
                            Id = (byte)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Maringá e Região",
                            Number = 44
                        },
                        new
                        {
                            Id = (byte)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Foz do Iguaçu e Região",
                            Number = 45
                        },
                        new
                        {
                            Id = (byte)27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Pato Branco e Região",
                            Number = 46
                        },
                        new
                        {
                            Id = (byte)28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Joinville e Região",
                            Number = 47
                        },
                        new
                        {
                            Id = (byte)29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Florianópolis e Região",
                            Number = 48
                        },
                        new
                        {
                            Id = (byte)30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Chapecó e Região",
                            Number = 49
                        },
                        new
                        {
                            Id = (byte)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Porto Alegre e Região",
                            Number = 51
                        },
                        new
                        {
                            Id = (byte)32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Pelotas e Região",
                            Number = 53
                        },
                        new
                        {
                            Id = (byte)33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Caxias do Sul e Região",
                            Number = 54
                        },
                        new
                        {
                            Id = (byte)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Santa Maria e Região",
                            Number = 55
                        },
                        new
                        {
                            Id = (byte)35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Distrito Federal",
                            Number = 61
                        },
                        new
                        {
                            Id = (byte)36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Goiânia e Região",
                            Number = 62
                        },
                        new
                        {
                            Id = (byte)37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Tocantins",
                            Number = 63
                        },
                        new
                        {
                            Id = (byte)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Rio Verde e Região",
                            Number = 64
                        },
                        new
                        {
                            Id = (byte)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Cuiabá e Região",
                            Number = 65
                        },
                        new
                        {
                            Id = (byte)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Rondonópolis e Região",
                            Number = 66
                        },
                        new
                        {
                            Id = (byte)41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Campo Grande e Região",
                            Number = 67
                        },
                        new
                        {
                            Id = (byte)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Acre",
                            Number = 68
                        },
                        new
                        {
                            Id = (byte)43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Rondônia",
                            Number = 69
                        },
                        new
                        {
                            Id = (byte)44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Salvador e Região",
                            Number = 71
                        },
                        new
                        {
                            Id = (byte)45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ilhéus e Região",
                            Number = 73
                        },
                        new
                        {
                            Id = (byte)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Juazeiro e Região",
                            Number = 74
                        },
                        new
                        {
                            Id = (byte)47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Feira de Santana e Região",
                            Number = 75
                        },
                        new
                        {
                            Id = (byte)48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Barreiras e Região",
                            Number = 77
                        },
                        new
                        {
                            Id = (byte)49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Sergipe",
                            Number = 79
                        },
                        new
                        {
                            Id = (byte)50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Recife e Região",
                            Number = 81
                        },
                        new
                        {
                            Id = (byte)51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Alagoas",
                            Number = 82
                        },
                        new
                        {
                            Id = (byte)52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Paraíba",
                            Number = 83
                        },
                        new
                        {
                            Id = (byte)53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Rio Grande do Norte",
                            Number = 84
                        },
                        new
                        {
                            Id = (byte)54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Fortaleza e Região",
                            Number = 85
                        },
                        new
                        {
                            Id = (byte)55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Teresina e Região",
                            Number = 86
                        },
                        new
                        {
                            Id = (byte)56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Petrolina e Região",
                            Number = 87
                        },
                        new
                        {
                            Id = (byte)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Região do Cariri",
                            Number = 88
                        },
                        new
                        {
                            Id = (byte)58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Piauí exceto Teresina",
                            Number = 89
                        },
                        new
                        {
                            Id = (byte)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Belém e Região",
                            Number = 91
                        },
                        new
                        {
                            Id = (byte)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Manaus e Região",
                            Number = 92
                        },
                        new
                        {
                            Id = (byte)61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Santarém e Região",
                            Number = 93
                        },
                        new
                        {
                            Id = (byte)62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Marabá e Região",
                            Number = 94
                        },
                        new
                        {
                            Id = (byte)63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Roraima",
                            Number = 95
                        },
                        new
                        {
                            Id = (byte)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Amapá",
                            Number = 96
                        },
                        new
                        {
                            Id = (byte)65,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Amazonas",
                            Number = 97
                        },
                        new
                        {
                            Id = (byte)66,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "São Luís e Região",
                            Number = 98
                        },
                        new
                        {
                            Id = (byte)67,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Imperatriz e Região",
                            Number = 99
                        });
                });

            modelBuilder.Entity("uBee.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("LocationId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("UserRole")
                        .HasColumnType("tinyint");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocationId = (byte)1,
                            Name = "Administrador",
                            Surname = "(built-in)",
                            UserRole = (byte)1,
                            _passwordHash = "BGcEw9QQNyBOf+rLF/xrMboZKa035bzLBqgGpTBJTrE8Fk2TwAMbe8N49SbaM2Ro"
                        },
                        new
                        {
                            Id = 10001,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocationId = (byte)1,
                            Name = "Cleber",
                            Surname = "(built-in)",
                            UserRole = (byte)2,
                            _passwordHash = "AxX8E7IFxv4rSTXU40IRjY6oPLVOq1y1tp0O5/vabDT/SPZlOWdktbiKCz2YLdzJ"
                        },
                        new
                        {
                            Id = 10002,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocationId = (byte)29,
                            Name = "Diego",
                            Surname = "(built-in)",
                            UserRole = (byte)3,
                            _passwordHash = "SlZEzmsPcuYfe8GRqN9lMLqv5KJpVmGpChaRoS5YVYQo/sSdeY6G5xj+nLF7zxJR"
                        },
                        new
                        {
                            Id = 10003,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocationId = (byte)1,
                            Name = "Lucas",
                            Surname = "(built-in)",
                            UserRole = (byte)3,
                            _passwordHash = "Wa+ZKmUcoWjcVPjQwVzY3tok2Thcejh2fGlA2lwZXv2oZ0NxL6Kb71NPYB8LP2De"
                        },
                        new
                        {
                            Id = 10004,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocationId = (byte)5,
                            Name = "Rafael",
                            Surname = "(built-in)",
                            UserRole = (byte)2,
                            _passwordHash = "tiNsfaj8kjCoJJcJeNyQqn03Ym4vuQldu3T+QL0AtJ9OzfkZcwo8UCd5+UcTDzEa"
                        },
                        new
                        {
                            Id = 10005,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocationId = (byte)4,
                            Name = "Wesley",
                            Surname = "(built-in)",
                            UserRole = (byte)3,
                            _passwordHash = "V8xyPoBEnUEUKLq5dxW5hqk8yiD42kfs1BMd8fKRkgrL9Ad1cA95US4avnA4TPYz"
                        });
                });

            modelBuilder.Entity("uBee.Domain.Entities.BeeContract", b =>
                {
                    b.HasOne("uBee.Domain.Entities.User", "User")
                        .WithMany("BeeContracts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("uBee.Domain.Entities.ContractedHive", b =>
                {
                    b.HasOne("uBee.Domain.Entities.BeeContract", null)
                        .WithMany("ContractedHives")
                        .HasForeignKey("BeeContractId");

                    b.HasOne("uBee.Domain.Entities.Hive", null)
                        .WithMany("ContractedHives")
                        .HasForeignKey("HiveId");

                    b.HasOne("uBee.Domain.Entities.BeeContract", "BeeContract")
                        .WithMany()
                        .HasForeignKey("IdBeeContract")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("uBee.Domain.Entities.Hive", "Hive")
                        .WithMany()
                        .HasForeignKey("IdHive")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeeContract");

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("uBee.Domain.Entities.Hive", b =>
                {
                    b.HasOne("uBee.Domain.Entities.User", "User")
                        .WithMany("Hives")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("uBee.Domain.Entities.User", b =>
                {
                    b.HasOne("uBee.Domain.Entities.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("Phone");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = 10000,
                                    Value = "11-983594962"
                                },
                                new
                                {
                                    UserId = 10001,
                                    Value = "11-992504176"
                                },
                                new
                                {
                                    UserId = 10002,
                                    Value = "48-91662888"
                                },
                                new
                                {
                                    UserId = 10003,
                                    Value = "11-994635700"
                                },
                                new
                                {
                                    UserId = 10004,
                                    Value = "15-998106370"
                                },
                                new
                                {
                                    UserId = 10005,
                                    Value = "14-981343266"
                                });
                        });

                    b.OwnsOne("uBee.Domain.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("CPF");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = 10000,
                                    Value = "80455390037"
                                },
                                new
                                {
                                    UserId = 10001,
                                    Value = "87622041068"
                                },
                                new
                                {
                                    UserId = 10002,
                                    Value = "40070242003"
                                },
                                new
                                {
                                    UserId = 10003,
                                    Value = "99872134057"
                                },
                                new
                                {
                                    UserId = 10004,
                                    Value = "46074925070"
                                },
                                new
                                {
                                    UserId = 10005,
                                    Value = "10096759070"
                                });
                        });

                    b.OwnsOne("uBee.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = 10000,
                                    Value = "admin@ubee.com"
                                },
                                new
                                {
                                    UserId = 10001,
                                    Value = "cleber@ubee.com"
                                },
                                new
                                {
                                    UserId = 10002,
                                    Value = "diego@ubee.com"
                                },
                                new
                                {
                                    UserId = 10003,
                                    Value = "lucas@ubee.com"
                                },
                                new
                                {
                                    UserId = 10004,
                                    Value = "rafael@ubee.com"
                                },
                                new
                                {
                                    UserId = 10005,
                                    Value = "wesley@ubee.com"
                                });
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("uBee.Domain.Entities.BeeContract", b =>
                {
                    b.Navigation("ContractedHives");
                });

            modelBuilder.Entity("uBee.Domain.Entities.Hive", b =>
                {
                    b.Navigation("ContractedHives");
                });

            modelBuilder.Entity("uBee.Domain.Entities.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("uBee.Domain.Entities.User", b =>
                {
                    b.Navigation("BeeContracts");

                    b.Navigation("Hives");
                });
#pragma warning restore 612, 618
        }
    }
}
